spring.application.name=ms-gateway
server.port=8080

# URIs de los microservicios (por defecto: nombres de contenedor de docker-compose)
services.user=${MS_USER_URI:http://ms-user:8090}
services.character=${MS_CHARACTER_URI:http://ms-character:8091}
services.item=${MS_ITEM_URI:http://ms-item:8092}
services.inventory=${MS_INVENTORY_URI:http://ms-inventory:8093}
services.quest=${MS_QUEST_URI:http://ms-quest:8094}
services.currency=${MS_CURRENCY_URI:http://ms-currency:8095}
services.shop=${MS_SHOP_URI:http://ms-shop:8096}
services.combat=${MS_COMBAT_URI:http://ms-combat:8097}

# JWT (mismo secreto que ms-user)
jwt.secret=${JWT_SECRET:change-this-super-secret-key-for-duoc-rpg-microservices-2026}
